### ISSUE TITLE
ffmpeg is False?

### ISSUE THREAD

**Issue by SudoR2spr** [AdibNikjou/MusicDownloader-Telegram-Bot#6]
/home/ubuntu/.local/lib/python3.10/site-packages/spotdl/console/entry_point. │
│ py:93 in entry_point                                                         │
│                                                                              │
│    92 │   if is_ffmpeg_installed(downloader_settings["ffmpeg"]) is False:    │
│ ❱  93 │   │   raise FFmpegError(                                             │

**Comment by AdibNikjou** [comment]
Thank you for reporting this issue. It appears that FFmpeg is not installed on your system.
FFmpeg is a required dependency for spotdl to function correctly.
To resolve this issue, please install FFmpeg:

- On Ubuntu/Debian: 
```bash
sudo apt install ffmpeg
```

- On Windows: 
Download from [Here](https://ffmpeg.org/download.html) and add it to your system PATH.

I'm also going to add this to dependencies in Readme file.
